faults:
  null_field:
    enabled: true
  missing_field:
    enabled: true
  empty_list:
    enabled: false
  empty_string:
    enabled: false
  invalid_data_type:
    enabled: false
  invalid_value:
    enabled: false
  http_method_change:
    enabled: false
  status_code_change:
    enabled: false
  delay_injection:
    enabled: false
    delay_ms: 500

url:
 exclude:
  - '*/login*'

endpoints:
 exclude:
  - '*/login*'

tests:
 exclude:
  - '*login*'

report:
 format: html
 output_path: "./reports/simulator-report.html"

